remote_theme: daattali/beautiful-jekyll

title: Common Sense Systems

navbar-links:
  About: "about-us"
  Services: "services"
  Blog: "blog"
  Contact: "contact"

title-img: /assets/img/logo-default.png

rss-description: Common Sense Systems has provided software engineering services to high-tech companies in the Seattle area since 1996.

share-links-active:
  twitter: true
  facebook: true
  linkedin: true

keywords: "software,coaching,embedded software,medical devices"

# Fill in your Google Analytics tag ID here
#gtag: "G-XXXXXXXXXX"

navbar-col: "#F2F2F2"
navbar-text-col: "#000000"
navbar-border-col: "#F2F2F2"
page-col: "#FFFFFF"
text-col: "#000000"
link-col: "#FF8A3D"
hover-col: "#FF8A3D"
footer-col: "#B6B6B6"
mobile-theme-col: "#FF8A3D"

site-css: "/assets/css/common-sense.css"

permalink: /blog/:title/
paginate_path: "/blog/page:num/"
timezone: "America/Los_Angeles"
markdown: kramdown
highlighter: rouge
paginate: 6

calendly-link: "john-sambrook/60-minute-meeting"
calendly-text: "Schedule time with John"

kramdown:
  input: GFM

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "John Sambrook"
      before-content: author.html
      after-content:
        - about-blurb.html
        - calendly.html
      social-share: true
  -
    scope:
      path: ""
    values:
      layout: "page"
      header-extra: wave.html
      after-content: calendly.html
      show-calendly-btn: true
      share-description: "Common Sense Systems has provided software engineering services to high-tech companies in the Seattle area since 1996."

plugins:
  - jekyll-paginate
  - jekyll-sitemap
