baseurl: "/c1146-common-sense"

remote_theme: daattali/beautiful-jekyll

title: Common Sense Systems

navbar-links:
  About: "about-us"
  Services: "services"
  Blog: "blog"
  Contact: "contact"

title-img: /assets/img/logo-default.png

rss-description: Common Sense Systems has provided software engineering services to high-tech companies in the Seattle area since 1996.

#keywords: "my,list,of,keywords,for,SEO"

navbar-col: "#F2F2F2"
navbar-text-col: "#000000"
navbar-border-col: "#F2F2F2"
page-col: "#FFFFFF"
text-col: "#000000"
link-col: "#FF8A3D"
hover-col: "#FF8A3D"
footer-col: "#B6B6B6"

share-links-active:
  twitter: true
  facebook: true
  linkedin: true

excerpt_length: 50
feed_show_excerpt: true
feed_show_tags: true

site-css: "/assets/css/common-sense.css"

calendly-link: "john-sambrook/30min"
calendly-text: "Schedule time with John"

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      social-share: true
  -
    scope:
      path: ""
    values:
      layout: "page"
      header-extra: wave.html
      after-content: calendly.html
      show-calendly-btn: true
      share-description: "Common Sense Systems has provided software engineering services to high-tech companies in the Seattle area since 1996."
